# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AccountabilityPods' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AccountabilityPods
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Analytics'
  pod 'Firebase/Firestore'

  target 'AccountabilityPodsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AccountabilityPodsUITests' do
    # Pods for testing
  end

end
