//
//  SkillsViewController.swift
//  AccountabilityPods
//
//  Created by MADRID, VASCO MADRID on 12/3/20.
//  Copyright © 2020 CapstoneGroup. All rights reserved.
//

import UIKit
import Firebase

class SkillsViewController: UIViewController {

    @IBOutlet weak var addSkillButton: UIButton!
    @IBOutlet weak var skillStackView: UIStackView!
    @IBOutlet weak var skillNameTextField: UITextField!
    @IBOutlet weak var skillDescriptionTextField: UITextField!
    @IBOutlet weak var doneAddingSkillButton: UIButton!
    @IBOutlet weak var cancelAddButton: UIButton!
    
    let db = Firestore.firestore()
    
    //This userID is acquired from the login event, and is the user's userID which is autogenerated by Firestore
    var userID = Constants.User.sharedInstance.userID;
    
    override func viewDidLoad() {
        super.viewDidLoad()

        // Do any additional setup after loading the view.
        setUpElements()
    }
    
    func setUpElements() {
        skillStackView.alpha = 0
    }

    /*
    // MARK: - Navigation

    // In a storyboard-based application, you will often want to do a little preparation before navigation
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        // Get the new view controller using segue.destination.
        // Pass the selected object to the new view controller.
    }
    */
    @IBAction func addSkillPressed(_ sender: Any) {
        skillStackView.alpha = 1;
    }
    @IBAction func donePressed(_ sender: Any) {
        var docRef = db.collection("users").document(userID).collection("SKILLS").addDocument(data: [
                        "creatorRef" : userID,
                        "skillName" : skillNameTextField.text ?? "N/A",
                        "skillDescription" : skillDescriptionTextField.text ?? "N/A"
                    ]) {err in
                        if let err = err {
                            print("The document was invalid for some reason? \(err)")
                        }
                        else{
                            print("Document added successfully.")
                            self.dismiss(animated:true, completion:nil)
                        }

        }
        // clear fields and hide add skill
        skillNameTextField.text = "Skill name ..."
        skillDescriptionTextField.text = "Skill description ..."
        skillStackView.alpha = 0;
    }
    @IBAction func cancelPressed(_ sender: Any) {
        skillNameTextField.text = "Skill name ..."
        skillDescriptionTextField.text = "Skill description ..."
        skillStackView.alpha = 0;
    }
    
}
