//
//  AddSkillViewController.swift
//  AccountabilityPods
//
//  Created by MADRID, VASCO MADRID on 12/3/20.
//  Copyright © 2020 CapstoneGroup. All rights reserved.
//

import UIKit
import Firebase

class AddSkillViewController: UIViewController, UITextViewDelegate, UITextFieldDelegate {

    @IBOutlet weak var addSkillStackView: UIStackView!
    @IBOutlet weak var skillNameTextField: UITextField!
    @IBOutlet weak var skillDescriptionTextField: UITextView!
    
    @IBOutlet weak var doneAddingButton: UIButton!
    
    let db = Firestore.firestore()
    
    //This userID is acquired from the login event, and is the user's userID which is autogenerated by Firestore
    var userID = Constants.User.sharedInstance.userID;
    
    
    override func viewDidLoad() {
        super.viewDidLoad()
        overrideUserInterfaceStyle = .light
        skillDescriptionTextField.delegate = self
        skillNameTextField.delegate = self
        editBoxes()
        // Do any additional setup after loading the view.
    }
    func editBoxes() {
        skillNameTextField.layer.cornerRadius = 15
        skillDescriptionTextField.layer.cornerRadius = 15
    }
    override func touchesBegan(_ touches: Set<UITouch>, with event: UIEvent?) {
        self.view.endEditing(true)
    }
    func textViewDidBeginEditing(_ textView: UITextView) {
        skillDescriptionTextField.text = ""
    }
    func textViewDidEndEditing(_ textView: UITextView) {
        if skillDescriptionTextField.text == "" {
            skillDescriptionTextField.text = "Skill description ..."
        }
        
    }
    func textFieldDidEndEditing(_ textField: UITextField) {
        // clear fields
        if skillNameTextField.text == "" {
            skillNameTextField.text = "Skill name ..."
        }
        
    }
    @IBAction func donePressed(_ sender: Any) {
        NotificationCenter.default.post(name: NSNotification.Name(rawValue: "OnEditSkill"), object: nil)
        _ = db.collection("users").document(userID).collection("SKILLS").addDocument(data: [
                        "creatorRef" : userID,
                        "skillName" : skillNameTextField.text ?? "N/A",
                        "skillDescription" : skillDescriptionTextField.text ?? "N/A"
                    ])
        {err in
                        if let err = err {
                            print("The document was invalid for some reason? \(err)")
                        }
                        else{
                            print("Document added successfully.")
                            self.dismiss(animated:true, completion:nil)
                        }

        }
        skillNameTextField.text = "Skill name ..."
        skillDescriptionTextField.text = "Skill description ..."
    }
        
    
    

    /*
    // MARK: - Navigation

    // In a storyboard-based application, you will often want to do a little preparation before navigation
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        // Get the new view controller using segue.destination.
        // Pass the selected object to the new view controller.
    }
    */

}
