//
//  SkillsViewController.swift
//  AccountabilityPods
//
//  Created by MADRID, VASCO MADRID on 12/3/20.
//  Copyright © 2020 CapstoneGroup. All rights reserved.
//
//  Description: Manages the own profile skills subview sub tabs
import UIKit
import Firebase

class SkillsViewController: UIViewController {

    // MARK: - UI Connectors
    
    /// The tabs that control whether view skills or add skills shows.
    @IBOutlet weak var segmentedController: UISegmentedControl!
    /// The subview to let user add a skill.
    @IBOutlet weak var addSkillContainer: UIView!
    /// The subview to let user view their own skills.
    @IBOutlet weak var viewSkillContainer: UIView!
    
    // MARK: - Class Variables 
    
    /// The firestore database
    let db = Firestore.firestore()
    /// This username is acquired from the login event, and is the user's userID which is autogenerated by Firestore
    var userID = Constants.User.sharedInstance.userID;
    
    // MARK: - Set up
    
    override func viewDidLoad() {
        super.viewDidLoad()
        // subview only works with light mode
        overrideUserInterfaceStyle = .light
    }
    
    /// Hides keyboard when other part of screen is tapped
    override func touchesBegan(_ touches: Set<UITouch>, with event: UIEvent?) {
        self.view.endEditing(true)
    }
    
    /// Sets up which subview shows depending on the selected tab 
    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        // switch the subview based on the selected tab index
        switch segmentedController.selectedSegmentIndex {
        case 0:
            self.viewSkillContainer.alpha = 1;
            self.addSkillContainer.alpha = 0;
        case 1:
            self.viewSkillContainer.alpha = 0;
            self.addSkillContainer.alpha = 1;
        default:
            break
        }
    }
    
    // MARK: - UI Functionality
    
    /// Changes subview depending on which tab was tapped.
    @IBAction func segmentedControllerPressed(_ sender: UISegmentedControl) {
        if sender.selectedSegmentIndex == 0 {
            UIView.animate(withDuration: 0.5, animations: {
                self.viewSkillContainer.alpha = 1;
                self.addSkillContainer.alpha = 0;
            })
        } else {
            UIView.animate(withDuration: 0.5, animations: {
                self.viewSkillContainer.alpha = 0;
                self.addSkillContainer.alpha = 1;
            })
        }
    }
    
}
