//
//  resourceCreationViewController.swift
//  AccountabilityPods
//
//  Created by Duncan Evans on 11/27/20. {Ported from other branch 11/25/20}
//  Copyright © 2020 CapstoneGroup. All rights reserved.
//
//  Description: Manages the "Share a Resource" page

import UIKit
import Firebase
class ResourceCreationViewController: UIViewController {
    
    // MARK: - Class Variables
    /// The firestore database
    let db = Firestore.firestore()
    /// This userID is acquired from the login event, and is the user's userID which is autogenerated by Firestore
    var userID = Constants.User.sharedInstance.userID;
    /// the user added description
    @IBOutlet weak var resourceDesc: UITextView!
    /// the user added resource name
    @IBOutlet weak var resourceName: UITextField!
    
    // MARK: - Set up
    
    override func viewDidLoad() {
        super.viewDidLoad()
        // Sets the page to only work in light mode
        overrideUserInterfaceStyle = .light
        // cosmetically changes text boxes
        resourceName.layer.cornerRadius = 5
        resourceDesc.layer.cornerRadius = 5

    }
    
    /// Hides the keyboard when other part of screen is tapped
    override func touchesBegan(_ touches: Set<UITouch>, with event: UIEvent?) {
        self.view.endEditing(true)
    }
    
    // MARK: - Button functionality
    
    /// Adds new post  database
    ///
    /// - Parameter sender: the add post button
    @IBAction func onAddPressed(_ sender: Any) {
        // check if resource has enough information
        if resourceName.text!.trimmingCharacters(in: .whitespacesAndNewlines) == "" || resourceDesc.text!.trimmingCharacters(in: .whitespacesAndNewlines) == "" {
            // resource information has not been entered
            let alertController = UIAlertController(title: "Need more info", message: "Resource name or description is missing. Please add this information", preferredStyle: .alert)
            alertController.addAction(UIAlertAction(title:"Got it!", style: .default, handler: nil))
            self.present(alertController, animated: true)
        } else {
            // create resource in databsae
            let timeStamp = Firebase.Timestamp().seconds
            _ = db.collection("users").document(userID).collection("POSTEDRESOURCES").addDocument(data: [
                        "creatorRef" : userID,
                        "imageLink" : "TODO", //TODO
                        "resourceDesc" : resourceDesc.text ?? "N/A",
                "resourceName" : resourceName.text ?? "N/A", "time": timeStamp
                    ]) {err in
                        if let err = err {
                            print("The document was invalid for some reason? \(err)")
                        }
                        else{
                            print("Document added successfully.")
                            NotificationCenter.default.post(name: NSNotification.Name(rawValue: "OnEditResource"), object: nil)
                            self.dismiss(animated:true, completion:nil)
                        }

                        }        }
        
    }
    
    /// Cancels adding post when tapped
    ///
    /// - Parameter sender: the cancel button
    @IBAction func cancelButton(_ sender: Any) {
        self.performSegue(withIdentifier: "cancelShareResource", sender: self)
    }

}
